# Generated by Django 2.2.5 on 2020-06-27 07:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('team', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlayerHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('total_match_played', models.PositiveSmallIntegerField(default=0)),
                ('total_run', models.PositiveSmallIntegerField(default=0)),
                ('highest_score', models.PositiveSmallIntegerField(default=0)),
                ('fifties', models.PositiveSmallIntegerField(default=0)),
                ('hundreds', models.PositiveSmallIntegerField(default=0)),
                ('total_wickets', models.PositiveSmallIntegerField(default=0)),
                ('strike_rate', models.FloatField(default=0.0)),
            ],
            options={
                'db_table': 'player_history',
            },
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('player_id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(db_index=True, max_length=50)),
                ('last_name', models.CharField(db_index=True, max_length=50)),
                ('image_uri', models.URLField(blank=True, null=True)),
                ('jersey_number', models.PositiveSmallIntegerField(default=0)),
                ('home_team', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='team.Team')),
                ('player_history', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='player.PlayerHistory')),
            ],
            options={
                'db_table': 'player',
            },
        ),
    ]
